---
- name: Another network playbook
  hosts: aristaswitchessecure
  gather_facts: no

  vars_files:
    - vault.yml

  tasks:

  - name: Harvest Arista facts
    eos_facts:
    when: ansible_network_os == 'eos'
